import type { Metadata } from "next";
import Link from "next/link";
import { MapPinned, Navigation, Route } from "lucide-react";

export const metadata: Metadata = { title: "このサイトについて", description: "どこランは、知らない土地でも走る場所を決めて、そのまま走り始められるランニングコース検索サービスです。" };

export default function AboutPage() {
  return <div className="mx-auto max-w-3xl px-4 py-12 md:px-6"><p className="font-bold text-brand-dark">ABOUT</p><h1 className="mt-2 text-3xl font-black sm:text-5xl">知らない土地でも、<br />迷わず走り始める。</h1><div className="mt-10 space-y-6 leading-8"><p>どこランは、旅先・出張先・大会遠征で「この近く、どこを走ればいい？」に答えるWebサービスです。走れる場所を探すだけでなく、代表コースとスタート地点まで確認して、そのまま走り始められます。</p><p>距離や高低差、信号、路面、夜の明るさ、設備を、場所ごとにひとつのページへ整理しています。知らない土地でも、自分に合うコースかを走る前に判断できます。</p></div><div className="mt-12 grid gap-4 sm:grid-cols-3">{[[MapPinned, "走る場所が決まる", "エリア・大会・条件から、候補をすぐに絞り込めます。"], [Route, "コースがわかる", "地図と距離、路面や設備を見て走り方を判断できます。"], [Navigation, "そのまま走り始める", "スタート地点まで案内し、対応コースはGPXでも持ち出せます。"]].map(([Icon, title, text]) => { const Component = Icon as typeof MapPinned; return <div key={String(title)} className="rounded-xl border border-line bg-cream p-5"><Component className="mb-4" /><h2 className="font-bold">{String(title)}</h2><p className="mt-2 text-sm leading-6 text-sub">{String(text)}</p></div>; })}</div><div className="mt-12 rounded-2xl border border-line bg-cream p-6 sm:p-8"><h2 className="text-xl font-bold">どこランのふたり</h2><div className="mt-6 grid gap-6 sm:grid-cols-2">{[["/characters/hashiro-happy.png", "ハシロー", "走るのが大好きな男の子。今日も新しいスポットを探して走り回っている。"], ["/characters/ran-smile.png", "ラン", "どこまでも軽やかに走る女の子。お気に入りのコースをたくさん知っている。"]].map(([src, name, text]) => <div key={name} className="flex items-center gap-5"><img src={src} alt={name} className="w-24 shrink-0" /><div><h3 className="font-bold">{name}</h3><p className="mt-1 text-sm leading-6 text-sub">{text}</p></div></div>)}</div></div><div className="mt-12 rounded-2xl bg-brand p-6 sm:p-8"><h2 className="text-xl font-bold">スポット掲載について</h2><p className="mt-3 leading-7">「このスポットを載せてほしい」というリクエストを受け付けています。情報の間違いの報告やその他のお問い合わせもこちらからどうぞ。</p><Link href="/contact" className="mt-5 inline-block rounded-lg bg-paper px-5 py-2.5 font-bold">リクエスト・お問い合わせ</Link></div></div>;
}
