import type { Metadata } from "next";
import Link from "next/link";
import { Database, MapPinned, Sparkles } from "lucide-react";

export const metadata: Metadata = { title: "このサイトについて", description: "どこランは、日本全国のランニングスポットを距離や設備から探せるデータベースです。" };

export default function AboutPage() {
  return <div className="mx-auto max-w-3xl px-4 py-12 md:px-6"><p className="font-bold text-brand-dark">ABOUT</p><h1 className="mt-2 text-3xl font-black sm:text-5xl">週末のランニングを、<br />もっと選びやすく。</h1><div className="mt-10 space-y-6 leading-8"><p>どこランは、日本中のランニングスポットを集めるWebサービスです。「週末、どこ走る？」と思ったとき、距離や高低差、信号、路面、夜の明るさ、設備から、自分に合う場所をすぐに見つけられます。</p><p>ランニングコースは無限に作れます。でも、走りに行く目的地はそれほど多くありません。そこで私たちは、公園や湖、河川敷といった「スポット」を主役にし、その場所を代表するコースの情報を整理しています。</p></div><div className="mt-12 grid gap-4 sm:grid-cols-3">{[[MapPinned, "スポットが主役", "目的地ごとに情報をひとつのページへ集約。"], [Database, "構造化された情報", "信号や路面、設備で迷わず比較。"], [Sparkles, "少しずつ全国へ", "運営が確認したスポットを順次掲載。"]].map(([Icon, title, text]) => { const Component = Icon as typeof MapPinned; return <div key={String(title)} className="rounded-xl border border-line bg-cream p-5"><Component className="mb-4" /><h2 className="font-bold">{String(title)}</h2><p className="mt-2 text-sm leading-6 text-sub">{String(text)}</p></div>; })}</div><div className="mt-12 rounded-2xl border border-line bg-cream p-6 sm:p-8"><h2 className="text-xl font-bold">どこランのふたり</h2><div className="mt-6 grid gap-6 sm:grid-cols-2">{[["/characters/hashiro-happy.png", "ハシロー", "走るのが大好きな男の子。今日も新しいスポットを探して走り回っている。"], ["/characters/ran-smile.png", "ラン", "どこまでも軽やかに走る女の子。お気に入りのコースをたくさん知っている。"]].map(([src, name, text]) => <div key={name} className="flex items-center gap-5"><img src={src} alt={name} className="w-24 shrink-0" /><div><h3 className="font-bold">{name}</h3><p className="mt-1 text-sm leading-6 text-sub">{text}</p></div></div>)}</div></div><div className="mt-12 rounded-2xl bg-brand p-6 sm:p-8"><h2 className="text-xl font-bold">スポット掲載について</h2><p className="mt-3 leading-7">「このスポットを載せてほしい」というリクエストを受け付けています。情報の間違いの報告やその他のお問い合わせもこちらからどうぞ。</p><Link href="/contact" className="mt-5 inline-block rounded-lg bg-paper px-5 py-2.5 font-bold">リクエスト・お問い合わせ</Link></div></div>;
}
